fix: only one child is reported for a process
remy/pstree pull request #16
Opened 2020-03-13 18:22 UTC by axxie

Fixes #15

2020-04-25 18:52 UTC, axxie commented
@remy, please take a look.

2020-04-25 20:21 UTC, remy commented
Waiting on changes as per comments on the code.

2020-04-26 07:00 UTC, axxie commented
> Waiting on changes as per comments on the code.

@remy, what comments on the code?
Could you, please, point out where are those comments?

2020-04-26 12:11 UTC, remy requested changes

2020-04-26 12:12 UTC, remy commented
For heaven's sake. Githubs UI for code reviews really isn't obvious. I posted the comment over a week ago, and returning now I see a tiny "pending" label. I've submitted the comments so you should be able to see them now (sorry about that)

2020-04-26 14:45 UTC, axxie commented on tests/index.test.js
> +      t.equal(children.length, 4);
Done.

2020-04-29 05:24 UTC, axxie commented
@remy, I've made the requested changes, please take a look.

2020-05-12 09:04 UTC, remy commented
Sorry it's taken so long to answer this. But the pstree.remy module is designed to _only_ get the sub-tree and not the main process. This is how it's used in nodemon too. This current PR thus adds an additional pid that isn't wanted in the list.

Sorry for wasting your time.

2020-05-12 09:14 UTC, axxie commented
> Sorry it's taken so long to answer this. But the pstree.remy module is designed to _only_ get the sub-tree and not the main process. This is how it's used in nodemon too. This current PR thus adds an additional pid that isn't wanted in the list.

@remy, I don't get it. This change doesn't get the pid of the main process. It only gets the sub-tree.

2020-05-12 09:16 UTC, axxie commented
> @remy, I don't get it. This change doesn't get the pid of the main process. It only gets the sub-tree.

Actually, cross it. I see it.
But the fix is trivial.
And the purpose of the change is to get all children, in contrast to what current implementation does.
Do you mind if I make a fix you to not return the main process?

2020-05-12 10:19 UTC, axxie commented
Apparently, there is some misunderstanding.
The purpose of this PR is to implement getting all children in cases, when some process in the chain has more than one child. Current implementation in the `master` doesn't do it, because it only remembers last parent. The proposed fix remembers all potential parents.

Returning the pid of the main process is unintentional side effect and it can be easily fixed.

2020-05-12 14:48 UTC, remy commented
Just trying to get it straight in my head (and I'm very careful about these low level changes because it has 100% affect on Mac and *nix users of nodemon).

The original test case you raised in #15 - this creates 2 sub-processes (off of `bash`). I'd expect pstree to return 2 pids.

I _think_ you're talking about another test case where you have a sub-sub-process? Is that right?

2020-05-12 14:58 UTC, i-keliukh commented
Actually, it is the same test case: it doesn't matter what process is parent of two children: the main process or some intermediate process in the chain.
In fact, originally I reproduced it with npm-run-all, not bash. As far as I remember, if  some npm task containt npm-run-all, the tree is like this:
```
nodemon
 +- npm
      +- npm-run-all
           +- npm
           |    +- node
           +- npm
                +- node
```

The issue with the current implementation is that once it went along one branch, it cannot return up to switch to another branch. This is because it only remembers one parent.

2020-05-16 13:14 UTC, remy commented on lib/tree.js
> -            rootPid = pid;
For future me, it was _this_ line (23) that caused the original problem of losing track of split trees.

2020-05-16 13:15 UTC, remy approved these changes

2020-05-16 13:16 UTC, merged

2020-05-16 13:25 UTC, remy commented
I can't release this at the moment, local tests are failing (as I was worried they would - it's reporting half the number of processes found). 

I'm investigating atm.

2020-05-16 14:59 UTC, remy commented
Live. What a fucking nightmare: https://github.com/remy/til/blob/master/node/spawn-sh-on-mac.md