zos: update child-tree retrieval algorithm and applicable tests
remy/pstree pull request #9
Opened 2019-06-03 19:42 UTC by gabylb

#### Checklist
- [x] npm install && npm test passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

#### Description of change
- the current algorithm for retrieving a given process's children tree assumes ps lists a parent process before its child; however, on z/OS this is not always the case; this update traverses the ps list recursively, and was applied only when running on z/OS
- one of the tests reads from /proc, which doesn't exist on z/OS and has been disabled

2019-06-24 16:47 UTC, gabylb commented
Hello @remy, please review/merge when you have a chance.

2020-05-16 13:24 UTC, remy requested changes

2020-05-16 13:24 UTC, remy commented on lib/tree.js
> +function find_kids_os390(rootPid, callback) {
Please rename to remove "kids" from this code. My own code policy after losing my own child is not to refer to children, kids, etc when meaning processes (this does appear in old code, but I'm making sure new code doesn't come in with it).

You'll also need to rebase your code from the latest PR - which isn't a huge change.

2020-05-16 13:26 UTC, remy commented
This should also ship with a test with a fixture that has the output from this zos `ps` report.

2020-06-17 12:19 UTC, gabylb commented
There was an issue with the rebase that I couldn't resolve, I'll open a new PR instead.

2020-06-17 12:19 UTC, closed without merging

2020-06-17 15:03 UTC, gabylb commented
New PR to replace this: https://github.com/remy/pstree/pull/17